# Saving and Loading NumPy Arrays

While not part of Python itself, the NumPy array library forms the basis for nearly all numeric computation within Python.  A few core features of the Python language have been specialized to accomodate the NumPy community and library.  The most notable examples of the language definition being modified for the sake of NumPy are the extended slice notation and the matrix multiply operator.

The *stride* argument to slices was added in Python 1.4 (long ago), but was not used by Python lists, tuples, or strings until 2.3 (still a long time).  The use of commas within compound slice descriptions is not used anywhere in Python's standard library but exists so that NumPy (and later other libraries) can utilize it.  Similarly, the operator `@` is not used anywhere in Python itself or its standard library, but was added so that NumPy can use it to denote matrix multiplication (some other libraries have utilized it for other purposes since then).

In [1]:
import pickle
import numpy as np

# Serializing with Pickle

Most Python objects, even those in extension libraries, can be serialized and deserialized with `pickle` module.  Classes are able to define a few protocol methods that allow them to interoperate with pickling.  For most purposes, pickle is fine for representing NumPy arrays.  Let us create one and roundtrip it.

In [2]:
arr = np.random.randint(1, 100, 1_000_000).reshape(100, 100, 100)
arr.shape

(100, 100, 100)

In [3]:
# Syntax extras for NumPy (matrix multiply dimensional slices)
arr[2:6, 4, 3:4] @ arr[8:9, 3, 4:8]

array([[5890, 8550, 1140, 6175],
       [1736, 2520,  336, 1820],
       [5704, 8280, 1104, 5980],
       [3720, 5400,  720, 3900]])

Dumping and loading a pickle of a NumPy array is the same as for any Python object.

In [4]:
pickle.dump(arr, open('tmp/arr.pkl', 'wb'))
arr2 = pickle.load(open('tmp/arr.pkl', 'rb'))
arr2[:2]

array([[[35, 18, 48, ..., 11, 42, 64],
        [95,  9, 55, ..., 84, 19, 60],
        [19, 75, 30, ..., 49, 11, 83],
        ...,
        [19, 80, 68, ..., 68, 59, 20],
        [ 8, 58, 85, ..., 81, 64, 41],
        [99, 66, 81, ..., 87, 35, 76]],

       [[63, 31, 58, ..., 85,  7, 32],
        [60, 41, 28, ...,  6, 92, 19],
        [66, 50, 50, ..., 24, 55, 79],
        ...,
        [59, 68, 13, ..., 40, 48, 57],
        [35, 18, 24, ..., 94, 17,  3],
        [85, 94, 10, ..., 63, 20, 94]]])

An advantage of pickles is that you might embed an array inside other structures, and pickle will handle that.

In [5]:
data = {'array': arr,
        'description': "A million random integers",
        'list': [5.4, 9.1, 3.4],
        'another_array': np.arange(5.0)}

data_bytes = pickle.dumps(data)
print(data_bytes[:35])

new_data = pickle.loads(data_bytes)
print("Description:", new_data['description'])
print("Extra data:", new_data['another_array'])

b'\x80\x04\x95\x92\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\x05array\x94\x8c\x15numpy.core.'
Description: A million random integers
Extra data: [0. 1. 2. 3. 4.]


# Serializing with `np.savetxt()`

For NumPy arrays that are 1-D or 2-D, you can save them as delimited files with the `savetxt()` function.  This is a convenient way to save data to CSV or TSV that might be read by DataFrame libraries or similar tools.  However, multi-dimensional arrays need to be reduced to 2-D to be stored in this manner.

In [6]:
np.savetxt('tmp/arr-txt.tsv', 
           arr.reshape(100_000, 10),
           delimiter='\t',
           fmt='%d',
           header='Original shape: (100, 100, 100)',
           comments='# ')

In [7]:
!head tmp/arr-txt.tsv

# Original shape: (100, 100, 100)
35	18	48	42	74	43	99	46	74	64
55	34	9	31	28	39	10	46	24	12
51	11	27	39	35	21	75	10	71	8
48	49	33	17	20	73	52	86	1	96
42	80	65	48	18	95	81	51	25	68
29	66	52	21	26	91	81	10	61	64
50	57	69	94	54	38	59	42	61	33
2	93	23	51	45	63	73	96	72	19
37	68	8	51	93	36	54	76	4	43


# Serializing with `np.save()`

The native NumPy serialization format is very simple and directly represents arrays on disk.  An `.npy` file is *slightly* faster to write than a pickle, and is *slightly* smaller on disk.  These differences are minimal and are swamped by disk caching effects and data size, respectively.  The actual advantage of `.npy` is precisely what it *does not* do; reading a serialized array will never instantiate custom classes, will never execute arbitrary code, and will never contain structures other than arrays.

In [8]:
%time np.save('tmp/arr.npy', arr)

CPU times: user 2.63 ms, sys: 20.4 ms, total: 23 ms
Wall time: 20.6 ms


In [9]:
arr3 = np.load('tmp/arr.npy')
arr3[:2]

array([[[35, 18, 48, ..., 11, 42, 64],
        [95,  9, 55, ..., 84, 19, 60],
        [19, 75, 30, ..., 49, 11, 83],
        ...,
        [19, 80, 68, ..., 68, 59, 20],
        [ 8, 58, 85, ..., 81, 64, 41],
        [99, 66, 81, ..., 87, 35, 76]],

       [[63, 31, 58, ..., 85,  7, 32],
        [60, 41, 28, ...,  6, 92, 19],
        [66, 50, 50, ..., 24, 55, 79],
        ...,
        [59, 68, 13, ..., 40, 48, 57],
        [35, 18, 24, ..., 94, 17,  3],
        [85, 94, 10, ..., 63, 20, 94]]])

# Serializing with `np.savez` and `np.savez_compressed`

An enhancement to the `.npy` format is the `.npz` format.  This uses a zipfile wrapper to aggregate multiple arrays in the same file.  Again, pickle could do this by putting them inside a dict or a list; the restriction is exactly the advantage for some cases.  In general, the compressed version is to be preferred in almost all cases; for the last decade, the extra CPU cycles to perform compression have been almost always faster than the extra time required to write more data to disk.

In [10]:
np.savez('tmp/arr', arr, data['another_array'])
np.savez_compressed('tmp/arr-compress', arr, data['another_array'])

The multiple arrays are available in a dict-like interface, and simply named as `arr_0`, `arr_1`, and so on.  You must store any mapping to the variable names used for these by separate means.

In [11]:
arr_data = np.load('tmp/arr.npz')
for name in arr_data:
    print(name, arr_data[name].shape, arr_data[name].dtype)

print(arr_data['arr_1'])

arr_0 (100, 100, 100) int64
arr_1 (5,) float64
[0. 1. 2. 3. 4.]


# File sizes

We serialized the same data using several different formats.  The CPU times taken for all of them are neglibigle; there are some notable patterns in disk usage.  

In [12]:
!ls -la tmp

total 27516
drwxr-xr-x 2 dmertz dmertz    4096 Jun 16 12:19 .
drwxr-xr-x 7 dmertz dmertz    4096 Jun 16 23:19 ..
-rw-r--r-- 1 dmertz dmertz 1245015 Jun 16 23:19 arr-compress.npz
-rw-r--r-- 1 dmertz dmertz 8000128 Jun 16 23:19 arr.npy
-rw-r--r-- 1 dmertz dmertz 8000546 Jun 16 23:19 arr.npz
-rw-r--r-- 1 dmertz dmertz 8000165 Jun 16 23:19 arr.pkl
-rw-r--r-- 1 dmertz dmertz 2909005 Jun 16 23:19 arr-txt.tsv


Notice the initially surprising fact that the text format is not the largest.  Because all of our integers were only two digits, they were each stored with two bytes for the numbers plus one for the delimiter.  In contrast, an int64 value requires 8 bytes to store uncompressed.  If the data contained values closer to `sys.maxsize`, i.e. 9,223,372,036,854,775,807, the size of the text version could easily become larger.